management:
  endpoint:
    health:
      show-details: when_authorized

## Server Properties
server:
  port: 8080
  servlet:
    context-path: /api/garbus

jwt:
  secret: ${JWT_SECRET_KEY}

spring:
  banner:
    location: ./banner.txt
  application:
    name: GARBUS

  #Java Persistence API
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: 'PUBLIC'

  # DB Connection Configuration
  datasource:
    initialization-mode: never
    url: ${DB_URL}
    username: ${DB_USR}
    password: ${DB_PSW}
    driverClassName: org.postgresql.Driver

events:
  problem_status:
    error: E
    error_others: O
    reactivated: R

mail:
  sender:
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    mail-api-key: ${MAIL_API_KEY}
  server:
    host: ${MAIL_HOST}
    port: ${PORT_HOST}